AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*

SpecialGlobalVars:
  Enabled: false

AsciiComments:
  Enabled: false

ClassLength:
  Max: 200

CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

LineLength:
  Max: 120
  Exclude:
    - spec/**/*

MethodLength:
  Max: 30

TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

